### PR TITLE
Update from Weblate

### PR DESCRIPTION
**Pull request by weblate**

### CODE REVIEW

**Comment by fujiwarat** [comment]
Currently ibus/ibus-anthy is a stable repository and [fujiwarat/ibus-anthy](https://github.com/fujiwarat/ibus-anthy) is the development repository.
Now I integrated this pull request to fujiwarat/ibus-anthy.

I modified all PO files to:
- Delete just added PO request
- Replace "Source translation" with "$LANGUAGE translation" in new PO files
- Replace "2008-2019 Takao Fujiwara" with "2008-2020 Takao Fujiwara"
- Update po/LINGUAS file
- Revert the null comment line between copyright lines and contributors line in PO header
- Append pull request ID to the Subject line

https://github.com/fujiwarat/ibus-anthy/commits/master

**Comment by Jibec** [comment]
@fujiwarat I locked the ibus-anthy project in Weblate. Please let it locked until I clean up the situation.
It looks like you deleted by mistake the changes done by translators in Weblate.

I understand you want Weblate to be plugged on https://github.com/fujiwarat/ibus-anthy
Is this correct?

If this is correct, I'll: export manually the translations done in https://github.com/ibus/ibus-anthy/pull/17
Then I'll reset Weblate repository and properly configure it to use https://github.com/fujiwarat/ibus-anthy
Then I'll import translators work in Weblate.
Then I'll change the component setting
Then you will close https://github.com/ibus/ibus-anthy/pull/17 and situation will be back to normal.

**Comment by fujiwarat** [comment]
I also noticed the problem.
Probably I may confuse you but try to explain the situation.
Right. my active development is https://github.com/fujiwarat/ibus-anthy and https://github.com/ibus/ibus-anthy is used when the new tarball is released.
And then I've ask people to file pull requests to ibus/ibus-anthy but not fujiwarat/ibus-anthy so that the issue IDs of pull request are generated in ibus/ibus-anthy.
The development repository means I've sometimes run `git push --force` to override the commits and it's useful for me to make the better commits.

I guess if Weblate will be plugged on fujiwarat/ibus-anthy, Weblate will create the pull requests in fujiwarat/ibus-anthy and the issue IDs of pull request will be conflict with ibus/ibus-anthy.

So now I'm thinking I won't close the pull requests from Weblate until I push all the changes of fujiwarat/ibus-anthy to ibus/ibus-anthy. The steps are:

1. Weblate create pull requests to ibus/ibus-anthy
2. I integrate the translation patches to fujiwarat/ibus-anthy upon the request but I don't close all the pull requests.
3. ibus-anthy's new release is comming
4. I make sure all the patches of pull requests of Weblate are integrated in fujiwarat/ibus-anthy
5. I push all changes of fujiwarat/ibus-anthy to ibus/ibus-anthy
6. I close all the pull requests of Weblate
7. I release the new ibus-anthy

I think this way works with Weblate and you don't have to change the Weblate repository.
Does it work for you?

**Comment by Jibec** [comment]
Keep it simple. Weblate is owner of translations files. Don't change weblate's commit and just change everything you like but no translation files in your fork.

If this bothers you, see what cockpit did to interact with weblate.

**Comment by fujiwarat** [comment]
>  Weblate is owner of translations files. Don't change weblate's commit and just change everything you like but no translation files in your fork.

No, I'm the owner of the translations and there are the bugs of Weblate and I have to change the PO files.
Anyway whether changing the PO files or not is not relative this problem.

**Comment by Jibec** [comment]
Whatever workflow you use is fine, here are the questions I have. But you are admin of your project in Weblate, you can set it up the way you want.

If developments are done in your repo and not the release one, how will you push the new strings to translate before the release?

If some developments are done out of you repo and directly to the release repo by other contributors, how will you push the new strings to translate before the release?

Did you create bug reports to weblate?

**Comment by fujiwarat** [comment]
> If developments are done in your repo and not the release one, how will you push the new strings to translate before the release?

I check out all the pull requests from github.com/ibus/ibus-anthy and I append the pull request ID to the commit subject.
E.g. if the pull request ID is #17, The subject will be likes "Update translation (Japanese) (#17)" and I push the translation patches to github.com/fujiwarat/ibus-anthy.
After all pull requests of translations are pushed to github.com/fujiwarat/ibus-anthy, I push all the changes of github.com/fujiwarat/ibus-anthy to github.com/ibus/ibus-anthy and create a new release in github.com/ibus/ibus-anthy. And the new tarball has ChangeLog which includes the change of "Update translation (Japanese) (#17)".
Since all updated translations are integrated in github.com/ibus/ibus-anthy, I got to Weblate and click "Reset".

> If some developments are done out of you repo and directly to the release repo by other contributors, how will you push the new strings to translate before the release?

I ask other translation contributers to update the development repo fujiwarat/ibus-anthy instead of the official repo ibus/ibus-anthy and the pull requests are merged to the development repo immediately before the developments are done. When I integrate pull requests of Weblate, I will use `msgcat --use-first` so that Weblate translations are prioritized. If other translations are conflicted, I will ask to update the translations with Weblate or make a pull request again.

> Did you create bug reports to weblate?

https://github.com/WeblateOrg/weblate/issues/3376

**Pull request closed without merging**
